CREATE TABLE IF NOT EXISTS whatsapp_admin_alert_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_request_id BIGINT NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    CONSTRAINT fk_whatsapp_admin_alert_outbox_booking_request
        FOREIGN KEY (booking_request_id)
            REFERENCES booking_requests(id)
            ON DELETE CASCADE,
    CONSTRAINT chk_whatsapp_admin_alert_outbox_status
        CHECK (status IN ('PENDING', 'RETRY', 'SENT', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_wa_admin_alert_outbox_due
    ON whatsapp_admin_alert_outbox (status, next_attempt_at, created_at);
