-- H2 version - Crear tabla catálogo de servicios
CREATE TABLE IF NOT EXISTS service_catalog (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(100)   NOT NULL,
    duration_minutes INTEGER        NOT NULL,
    price            DECIMAL(10,2)  NOT NULL,
    description      VARCHAR(300),
    active           BOOLEAN        NOT NULL DEFAULT true,
    display_order    INTEGER        NOT NULL DEFAULT 0
);

-- Insertar servicios iniciales (H2 compatible)
MERGE INTO service_catalog (id, name, duration_minutes, price, active, display_order)
VALUES
(1,  'Manicure + Brillo',            60,  10000, true, 1),
(2,  'Manicure Semi-Permanente',      90,  20000, true, 2),
(3,  'Manicure Men',                  90,  15000, true, 3),
(4,  'Kapping Gel',                  120,  22000, true, 4),
(5,  'Soft Gel',                     150,  27000, true, 5),
(6,  'Polygel Esculpido',            210,  35000, true, 6),
(7,  'Pedicure + Esmaltado',          90,  22000, true, 7),
(8,  'Pedicure + Esmaltado + Spa',   150,  25000, true, 8),
(9,  'Nail Art',                     240,  30000, true, 9),
(10, 'Retiro de Esmalte',             60,   7000, true, 10);

-- Modificar tabla appointments (solo si la columna no existe)
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS service_catalog_id BIGINT;

-- Migrar datos existentes (si los hay) al primer servicio
UPDATE appointments SET service_catalog_id = 1 WHERE service_catalog_id IS NULL;

-- Hacer la columna NOT NULL
ALTER TABLE appointments ALTER COLUMN service_catalog_id SET NOT NULL;

-- Agregar foreign key
ALTER TABLE appointments ADD CONSTRAINT IF NOT EXISTS fk_appointment_service 
    FOREIGN KEY (service_catalog_id) REFERENCES service_catalog(id);

-- Eliminar columna vieja
ALTER TABLE appointments DROP COLUMN IF EXISTS service_type;
