CREATE TABLE IF NOT EXISTS notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT,
    customer_id BIGINT,
    channel VARCHAR(20) NOT NULL, -- 'EMAIL', 'WHATSAPP'
    recipient VARCHAR(100) NOT NULL,
    subject VARCHAR(200),
    content TEXT,
    wamid VARCHAR(100), -- WhatsApp Message ID
    status VARCHAR(20) DEFAULT 'SENT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_logs_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL,
    CONSTRAINT fk_notification_logs_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_notification_logs_appointment ON notification_logs(appointment_id);
CREATE INDEX IF NOT EXISTS idx_notification_logs_customer ON notification_logs(customer_id);
CREATE INDEX IF NOT EXISTS idx_notification_logs_wamid ON notification_logs(wamid);
