-- H2 version - Tabla de usuarios para autenticacion
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    email VARCHAR(100),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    role VARCHAR(20) NOT NULL DEFAULT 'ADMIN',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indice para busqueda rapida por username
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- Insertar usuario admin por defecto (password: changeme)
-- BCrypt hash de "changeme" con strength 10
MERGE INTO users (username, password, full_name, email, enabled, role)
KEY(username)
VALUES (
    'admin',
    '$2a$10$Gzs9U5CRc5uVVtQc5D0vEu.hhzpPLIDh3TP1cFVHkHJ.Kq/e3FFGW',
    'Administrador',
    'admin@bunnycure.cl',
    TRUE,
    'ADMIN'
);
