-- V63: Create incoming_whatsapp_messages table for storing client messages from WhatsApp (H2)
CREATE TABLE incoming_whatsapp_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wamid VARCHAR(120) UNIQUE,
    from_phone VARCHAR(30) NOT NULL,
    sender_name VARCHAR(120),
    content CLOB NOT NULL,
    message_type VARCHAR(30) DEFAULT 'text' NOT NULL,
    customer_id BIGINT,
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_incoming_wa_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL
);

CREATE INDEX idx_incoming_wa_msgs_phone ON incoming_whatsapp_messages(from_phone);
CREATE INDEX idx_incoming_wa_msgs_created ON incoming_whatsapp_messages(created_at DESC);
CREATE INDEX idx_incoming_wa_msgs_read ON incoming_whatsapp_messages(is_read);
CREATE INDEX idx_incoming_wa_msgs_customer ON incoming_whatsapp_messages(customer_id);
