-- V64: Create whatsapp_outbox_messages table for failed / pending WhatsApp messages (H2)
CREATE TABLE IF NOT EXISTS whatsapp_outbox_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT,
    customer_id BIGINT,
    recipient_phone VARCHAR(30) NOT NULL,
    message_type VARCHAR(20) DEFAULT 'TEMPLATE' NOT NULL,
    template_name VARCHAR(100),
    language_code VARCHAR(20) DEFAULT 'es_CL',
    header_param VARCHAR(200),
    body_params_json CLOB,
    text_content CLOB,
    status VARCHAR(20) DEFAULT 'FAILED' NOT NULL,
    attempt_count INTEGER DEFAULT 1 NOT NULL,
    last_error CLOB,
    last_attempt_at TIMESTAMP,
    sent_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_wa_outbox_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE SET NULL,
    CONSTRAINT fk_wa_outbox_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
    CONSTRAINT chk_wa_outbox_status CHECK (status IN ('PENDING', 'RETRY', 'SENT', 'FAILED', 'DISCARDED'))
);

CREATE INDEX idx_wa_outbox_status ON whatsapp_outbox_messages(status);
CREATE INDEX idx_wa_outbox_created_at ON whatsapp_outbox_messages(created_at DESC);
CREATE INDEX idx_wa_outbox_recipient ON whatsapp_outbox_messages(recipient_phone);
CREATE INDEX idx_wa_outbox_appointment ON whatsapp_outbox_messages(appointment_id);
