-- Fix: Usar secuencia explícita para booking_requests
-- Problema: GENERATED BY DEFAULT AS IDENTITY no está generando IDs
-- Problema adicional: Asegurar que el INCREMENT BY sea 1 (no 50)
-- Solución: Crear secuencia con INCREMENT BY 1 explícito

-- Crear secuencia para booking_requests si no existe
CREATE SEQUENCE IF NOT EXISTS booking_requests_seq START WITH 1 INCREMENT BY 1;

-- Si la secuencia ya existe con increment diferente, recrearla
DROP SEQUENCE IF EXISTS booking_requests_seq CASCADE;
CREATE SEQUENCE booking_requests_seq START WITH 1 INCREMENT BY 1;

-- Alterar tabla para usar la secuencia
ALTER TABLE booking_requests 
  ALTER COLUMN id SET DEFAULT nextval('booking_requests_seq');

-- Asegurar que la secuencia continúa desde el máximo ID actual
SELECT setval('booking_requests_seq', COALESCE((SELECT MAX(id) FROM booking_requests), 0) + 1);
