-- Fix: Usar secuencia explícita para booking_requests
-- Problema: GENERATED BY DEFAULT AS IDENTITY no está generando IDs
-- Solución: Crear secuencia y usarla explícitamente

-- Crear secuencia para booking_requests
CREATE SEQUENCE IF NOT EXISTS booking_requests_seq START WITH 1 INCREMENT BY 1;

-- Alterar tabla para usar la secuencia
ALTER TABLE booking_requests 
  ALTER COLUMN id SET DEFAULT nextval('booking_requests_seq');

-- Asegurar que la secuencia continúa desde el máximo ID actual
SELECT setval('booking_requests_seq', COALESCE((SELECT MAX(id) FROM booking_requests), 0) + 1);
