-- Fix: Usar secuencia explícita para customers
-- Problema: GENERATED BY DEFAULT AS IDENTITY no está generando IDs
-- Solución: Crear secuencia y usarla explícitamente

-- Crear secuencia para customers
CREATE SEQUENCE IF NOT EXISTS customers_seq START WITH 1 INCREMENT BY 1;

-- Alterar tabla para usar la secuencia
ALTER TABLE customers 
  ALTER COLUMN id SET DEFAULT nextval('customers_seq');

-- Asegurar que la secuencia continúa desde el máximo ID actual
SELECT setval('customers_seq', COALESCE((SELECT MAX(id) FROM customers), 0) + 1);
