-- Fix: Usar secuencia explícita para customers
-- Problema: GENERATED BY DEFAULT AS IDENTITY no está generando IDs
-- Problema adicional: Asegurar que el INCREMENT BY sea 1 (no 50)
-- Solución: Crear secuencia con INCREMENT BY 1 explícito

-- Crear secuencia para customers si no existe
CREATE SEQUENCE IF NOT EXISTS customers_seq START WITH 1 INCREMENT BY 1;

-- Si la secuencia ya existe con increment diferente, recrearla
DROP SEQUENCE IF EXISTS customers_seq;
CREATE SEQUENCE customers_seq START WITH 1 INCREMENT BY 1;

-- Alterar tabla para usar la secuencia
ALTER TABLE customers 
  ALTER COLUMN id SET DEFAULT nextval('customers_seq');

-- Asegurar que la secuencia continúa desde el máximo ID actual
SELECT setval('customers_seq', COALESCE((SELECT MAX(id) FROM customers), 0) + 1);