-- Fix: Crear secuencia explícita para appointments
-- Problema: GENERATED BY DEFAULT AS IDENTITY no está funcionando correctamente con Hibernate
-- Solución: Crear secuencia y usarla explícitamente

-- Crear secuencia para appointments si no existe
CREATE SEQUENCE IF NOT EXISTS appointments_seq START WITH 1 INCREMENT BY 1;

-- Si la secuencia ya existe con increment diferente, recrearla
DROP SEQUENCE IF EXISTS appointments_seq CASCADE;
CREATE SEQUENCE appointments_seq START WITH 1 INCREMENT BY 1;

-- Alterar tabla para usar la secuencia
ALTER TABLE appointments 
  ALTER COLUMN id SET DEFAULT nextval('appointments_seq');

-- Asegurar que la secuencia continúa desde el máximo ID actual
SELECT setval('appointments_seq', COALESCE((SELECT MAX(id) FROM appointments), 0) + 1);
