-- ==========================================================
-- V58: Create Tenants table and Multi-Tenant architecture
-- Soporte para multi-salón con dominios propios y aislamiento de datos.
-- ==========================================================

-- 1. Tabla maestra de salones / tenants
CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(60) UNIQUE NOT NULL,
    custom_domain VARCHAR(120) UNIQUE,
    rut VARCHAR(20),
    phone VARCHAR(30),
    email VARCHAR(120),
    address VARCHAR(255),
    logo_url VARCHAR(500),
    primary_color VARCHAR(20) DEFAULT '#d48b70',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    plan_tier VARCHAR(30) NOT NULL DEFAULT 'STANDARD',
    whatsapp_phone_id VARCHAR(100),
    whatsapp_token VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tenants_custom_domain ON tenants(custom_domain);
CREATE INDEX IF NOT EXISTS idx_tenants_slug ON tenants(slug);

-- 2. Insertar Tenant inicial BunnyCure por defecto (si no existe)
INSERT INTO tenants (id, name, slug, custom_domain, email, phone, active, plan_tier)
SELECT 1, 'BunnyCure Studio', 'bunnycure', 'app.bunnycure.cl', 'contacto@bunnycure.cl', '+56983692046', TRUE, 'PRO'
WHERE NOT EXISTS (SELECT 1 FROM tenants WHERE id = 1);

-- 3. Agregar columna tenant_id a las tablas principales con valor por defecto 1
ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE appointments ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE service_catalog ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE customer_service_records ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE booking_requests ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE gift_cards ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL DEFAULT 1;

-- 4. Índices de rendimiento compuestos por Tenant
CREATE INDEX IF NOT EXISTS idx_customers_tenant_phone ON customers(tenant_id, phone);
CREATE INDEX IF NOT EXISTS idx_customers_tenant_name ON customers(tenant_id, full_name);
CREATE INDEX IF NOT EXISTS idx_appointments_tenant_date ON appointments(tenant_id, appointment_date, appointment_time);
CREATE INDEX IF NOT EXISTS idx_appointments_tenant_specialist ON appointments(tenant_id, specialist_id, appointment_date);
CREATE INDEX IF NOT EXISTS idx_users_tenant_username ON users(tenant_id, username);
CREATE INDEX IF NOT EXISTS idx_booking_requests_tenant_status ON booking_requests(tenant_id, status, created_at);
