-- Tabla de solicitudes de reserva desde el portal publico
CREATE TABLE booking_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    email VARCHAR(150),
    service_id BIGINT NOT NULL,
    preferred_date DATE NOT NULL,
    preferred_block VARCHAR(50),
    notes VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    appointment_id BIGINT,
    rejection_reason VARCHAR(300),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    
    CONSTRAINT fk_booking_request_service FOREIGN KEY (service_id) 
        REFERENCES service_catalog(id) ON DELETE RESTRICT,
    CONSTRAINT fk_booking_request_appointment FOREIGN KEY (appointment_id) 
        REFERENCES appointments(id) ON DELETE SET NULL,
    CONSTRAINT chk_booking_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

-- Indices para busquedas frecuentes
CREATE INDEX idx_booking_request_status ON booking_requests(status);
CREATE INDEX idx_booking_request_date ON booking_requests(preferred_date);
CREATE INDEX idx_booking_request_created ON booking_requests(created_at);
